spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pastebin
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  cloud:
    openfeign:
      httpclient:
        connection-timeout: 5000

server:
  error:
    include-message: always
